/**
 * Script kiểm tra metadata ảnh để phát hiện dấu vết AI
 * Quét: EXIF, PNG tEXt chunks, XMP data
 */
const fs = require('fs');
const path = require('path');

const IMAGE_DIR = path.join(__dirname, '..', 'public', 'images');
const AI_KEYWORDS = [
  'stable diffusion', 'midjourney', 'dall-e', 'dalle', 'openai',
  'comfyui', 'automatic1111', 'invoke', 'novelai', 'nai diffusion',
  'dreamstudio', 'stability.ai', 'civitai', 'lora', 'checkpoint',
  'sampler', 'cfg scale', 'steps', 'seed', 'negative prompt',
  'prompt', 'model:', 'generated by', 'ai generated', 'ai-generated',
  'adobe firefly', 'firefly', 'bing image creator', 'copilot',
  'gemini', 'imagen', 'flux', 'ideogram', 'leonardo',
  'c2pa', 'contentcredentials', 'content credentials',
  'digital source type', 'trainedAlgorithmicMedia',
  'compositeWithTrainedAlgorithmicMedia',
  'made with ai', 'ai_generated', 'dream', 'txt2img', 'img2img',
  'tEXt', 'iTXt', 'parameters', 'comment',
  // IPTC / XMP AI markers
  'digitalsourcetype', 'aigenerated',
];

let totalFiles = 0;
let flaggedFiles = 0;
const results = [];

function scanPNGChunks(filePath) {
  const buf = fs.readFileSync(filePath);
  const findings = [];
  
  // Check PNG signature
  if (buf[0] !== 0x89 || buf[1] !== 0x50) return findings;
  
  let offset = 8; // Skip PNG signature
  while (offset < buf.length - 12) {
    const chunkLength = buf.readUInt32BE(offset);
    const chunkType = buf.slice(offset + 4, offset + 8).toString('ascii');
    
    // Check text-based chunks that often contain AI metadata
    if (['tEXt', 'iTXt', 'zTXt'].includes(chunkType)) {
      try {
        const chunkData = buf.slice(offset + 8, offset + 8 + Math.min(chunkLength, 4096)).toString('utf-8', 0, Math.min(chunkLength, 4096));
        
        // Check for AI-related keywords
        const lowerData = chunkData.toLowerCase();
        for (const keyword of AI_KEYWORDS) {
          if (lowerData.includes(keyword.toLowerCase())) {
            findings.push({
              chunk: chunkType,
              keyword: keyword,
              preview: chunkData.substring(0, 200).replace(/\0/g, ' | ')
            });
          }
        }
        
        // Even if no keyword match, flag any tEXt/iTXt chunk with suspicious content
        if (chunkData.length > 10) {
          const hasParams = lowerData.includes('parameters') || lowerData.includes('prompt') || 
                           lowerData.includes('model') || lowerData.includes('software');
          if (hasParams) {
            findings.push({
              chunk: chunkType,
              keyword: '(suspicious text chunk)',
              preview: chunkData.substring(0, 300).replace(/\0/g, ' | ')
            });
          }
        }
      } catch (e) {}
    }
    
    // Check for XMP data (eXIf or custom chunks)
    if (chunkType === 'eXIf' || chunkType === 'iCCP') {
      try {
        const chunkData = buf.slice(offset + 8, offset + 8 + Math.min(chunkLength, 4096)).toString('utf-8', 0, Math.min(chunkLength, 4096));
        const lowerData = chunkData.toLowerCase();
        for (const keyword of AI_KEYWORDS) {
          if (lowerData.includes(keyword.toLowerCase())) {
            findings.push({
              chunk: chunkType,
              keyword: keyword,
              preview: chunkData.substring(0, 200).replace(/[\x00-\x1f]/g, '.')
            });
          }
        }
      } catch (e) {}
    }
    
    offset += 12 + chunkLength; // 4 length + 4 type + data + 4 CRC
  }
  
  return findings;
}

function scanJPEGExif(filePath) {
  const buf = fs.readFileSync(filePath);
  const findings = [];
  
  // Check JPEG signature
  if (buf[0] !== 0xFF || buf[1] !== 0xD8) return findings;
  
  // Scan for text content in EXIF/XMP
  try {
    const content = buf.toString('utf-8', 0, Math.min(buf.length, 65536));
    const lowerContent = content.toLowerCase();
    for (const keyword of AI_KEYWORDS) {
      if (lowerContent.includes(keyword.toLowerCase())) {
        const idx = lowerContent.indexOf(keyword.toLowerCase());
        findings.push({
          chunk: 'EXIF/XMP',
          keyword: keyword,
          preview: content.substring(Math.max(0, idx - 20), Math.min(content.length, idx + 100)).replace(/[\x00-\x1f]/g, '.')
        });
      }
    }
  } catch (e) {}
  
  return findings;
}

function scanWebPMeta(filePath) {
  const buf = fs.readFileSync(filePath);
  const findings = [];
  
  // Check RIFF/WEBP signature
  if (buf.slice(0, 4).toString() !== 'RIFF' || buf.slice(8, 12).toString() !== 'WEBP') return findings;
  
  try {
    const content = buf.toString('utf-8', 0, Math.min(buf.length, 65536));
    const lowerContent = content.toLowerCase();
    for (const keyword of AI_KEYWORDS) {
      if (lowerContent.includes(keyword.toLowerCase())) {
        const idx = lowerContent.indexOf(keyword.toLowerCase());
        findings.push({
          chunk: 'WebP-XMP/EXIF',
          keyword: keyword,
          preview: content.substring(Math.max(0, idx - 20), Math.min(content.length, idx + 100)).replace(/[\x00-\x1f]/g, '.')
        });
      }
    }
  } catch (e) {}
  
  return findings;
}

function walkDir(dir) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      walkDir(fullPath);
    } else {
      const ext = path.extname(entry.name).toLowerCase();
      if (['.png', '.jpg', '.jpeg', '.webp'].includes(ext)) {
        totalFiles++;
        let findings = [];
        
        if (ext === '.png') findings = scanPNGChunks(fullPath);
        else if (ext === '.jpg' || ext === '.jpeg') findings = scanJPEGExif(fullPath);
        else if (ext === '.webp') findings = scanWebPMeta(fullPath);
        
        if (findings.length > 0) {
          flaggedFiles++;
          // Deduplicate findings by keyword
          const unique = [];
          const seen = new Set();
          for (const f of findings) {
            const key = f.keyword;
            if (!seen.has(key)) {
              seen.add(key);
              unique.push(f);
            }
          }
          results.push({
            file: path.relative(IMAGE_DIR, fullPath),
            findings: unique
          });
        }
      }
    }
  }
}

console.log('=== KIỂM TRA METADATA ẢNH AI ===\n');
walkDir(IMAGE_DIR);

console.log(`Tổng số file ảnh: ${totalFiles}`);
console.log(`File có dấu vết AI: ${flaggedFiles}`);
console.log(`File sạch: ${totalFiles - flaggedFiles}\n`);

if (results.length > 0) {
  console.log('--- CÁC FILE CÓ DẤU VẾT AI ---\n');
  for (const r of results) {
    console.log(`🔴 ${r.file}`);
    for (const f of r.findings) {
      console.log(`   Chunk: ${f.chunk} | Keyword: "${f.keyword}"`);
      console.log(`   Preview: ${f.preview.substring(0, 120)}`);
    }
    console.log('');
  }
} else {
  console.log('✅ Tất cả ảnh đều SẠCH metadata AI.');
}
